server:
    port: 8080
    servlet:
        context-path: /player

spring:
    datasource:
        url: ${DB_MUSICPLAYER_URL}
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}

jwt:
    signerKey: "silGlN6mtlv51vS5+mMORKv6vRxqU5GAbmJU2ukJY+x/fBW94ZqJOXlzTWSln1Oj"